// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Note.Backend.Infrastructure.SQLServer.Context.NutritionData;

#nullable disable

namespace Note.Backend.Infrastructure.SQLServer.Migrations.RecipeNutritionData
{
    [DbContext(typeof(RecipeNutritionDataContext))]
    [Migration("20231005174144_NutritionData")]
    partial class NutritionData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Note.Backend.Infrastructure.SQLServer.Models.RecipeNutritionDataDto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("TotalCalories")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TotalCarbCalories")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TotalCarbWeight")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TotalFatCalories")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TotalFatWeight")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TotalProteinCalories")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TotalProteinWeight")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("RecipeNutritionData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
